name: Deploy portfolio

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
    - run: npm ci
    - run: npm test -- --passWithNoTests
    - run: npm run build
    - name: Deploy to Vercel
      run: npx vercel --prod --token=${{ secrets.GITHUB_TOKEN }}
